name: swapit_marketplace
description: Second-hand marketplace app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  google_fonts: ^6.1.0
  dotted_border: ^2.1.0
  intl: ^0.19.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in:
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # UI & Utilities
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  timeago: ^3.7.1

  # Store image online
  cloudinary_public: ^0.23.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
